<?php
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * THIS IS MODIFIED FOR YOUZAN, ANY PROBLEM PLS CONTACT lanhu(zhangyuanhao@qima-inc.com)
 * qingjiao(qingjiao@qima-inc.com) & xiao'er(shiyu@qima-inc.com)
 * @generated
 */

namespace Com\Youzan\Nova\Framework\Generic\Interfaces;

interface GenericService {
  /**
   * @param \Com\Youzan\Nova\Framework\Generic\Service\GenericRequest $request
   * @return string
   */
  public function invoke(\Com\Youzan\Nova\Framework\Generic\Service\GenericRequest $request);
}

